name: 'build'

on:
  push:
    branches:
    - master
  pull_request:

  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker tags'
        required: true
        default: "latest"

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          echo "build ghcr.io/${GITHUB_REPOSITORY}:latest"
          docker build -t ghcr.io/${GITHUB_REPOSITORY}:latest .

      - name: Setup GitHub Container Registry
        run: echo $CR_PAT | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
        env:
          CR_PAT: ${{ secrets.PAT }}

      - name: push to GitHub Container Registry
        run: docker push ghcr.io/${GITHUB_REPOSITORY}:latest

    # - name: build Image
    #   run: |
    #     echo $CR_PAT | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
    #   env:
    #     CR_PAT: ${{ secrets.PAT }}

    #   - name: Login to Github Packages
    #     uses: docker/login-action@v1
    #     with:
    #       registry: ghcr.io
    #       username: ${GITHUB_ACTOR}
    #       password: ${{ secrets.PAT }}

    #   - name: Image digest

    #     run: echo "build ghcr.io/${GITHUB_REPOSITORY}:latest"

    #   - name: Build and push
    #     uses: docker/build-push-action@v2
    #     with:
    #       push: true
    #       tags: |
    #         ghcr.io/${GITHUB_REPOSITORY}:latest


      # - name: 'Build dockerimage'
      #   uses: docker/build-push-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: "${GITHUB_ACTOR}"
      #     password: ${{ secrets.PAT }}
      #     repository: ${GITHUB_ACTOR}/${{ github.event.repository.name }}
      #     tags: "${{ github.event.inputs.tag }}"
