name: 'build'

on:
  push:
    branches:
    - master
  pull_request:

  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker tags'
        required: true
        default: "latest"

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2

      - name: Print event data
        run: echo "$EVENT"
        env:
          EVENT: ${{ toJSON( github.event ) }}

      - run: echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
        shell: bash

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${GITHUB_ACTOR}
          password: ${{ secrets.PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${GITHUB_REPOSITORY}:latest


      # - name: 'Build dockerimage'
      #   uses: docker/build-push-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: "${GITHUB_ACTOR}"
      #     password: ${{ secrets.PAT }}
      #     repository: ${GITHUB_ACTOR}/${{ github.event.repository.name }}
      #     tags: "${{ github.event.inputs.tag }}"
